version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: this_is_a_test_password
      MYSQL_DATABASE: talatrivia
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
