version: '3.8'

services:
  talatrivia_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talatrivia_api
    restart: always
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: this_is_a_test_password
      MYSQL_DATABASE: talatrivia
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
