name: Run Unit Test via Pytest

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test docker
        run: docker --version

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start MariaDB
        run: docker-compose up -d

      - name: Simple wait for MariaDB
        run: | 
          sleep 25
          docker logs mariadb

      - name: Run uvicorn
        run: |
          cd project
          uvicorn main:app --host 0.0.0.0 &
          sleep 5

      - name: Test with pytest
        run: |
          cd project/tests
          pytest -s -vvl
