name: Run Unit Test via Pytest

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run uvicorn
        run: |
          cd project/app
          uvicorn main:app --reload --host 0.0.0.0
      - name: Test with pytest
        run: |
          cd project/tests
          coverage run -m pytest  -v -s
